name: feast-env
dependencies:
    - python=3.6
    - pip=21.1
    - sqlalchemy=1.4.22
    - pyodbc=4.0.31
    - pymssql=2.1.5
    - ipykernel=5.3.4
    - scikit-learn=0.24.2
    - pip:
        - azureml-sdk==1.32.0
        - azureml-mlflow==1.32.0
        - redis==3.5.3
        - redis-py-cluster==2.1.3
        - git+https://github.com/samuel100/feast.git@samuel100-azregstore#egg=feast&subdirectory=sdk/python
        - azure-storage-blob